spring:
  datasource:         # Oracle dataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dblab.dongduk.ac.kr:1521/orclpdb
    #    url: jdbc:oracle:thin:@dblab_high?TNS_ADMIN=C:/Oracle/Wallet_DBLab    # use Oracle Wallet
    #    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=...))(connect_data=(service_name=...))(security=(ssl_server_dn_match=yes)))
    username: ss240205
    password: 110818
    hikari:          # HikariCP settings
      maximumPoolSize: 3
      connectionTimeout: 3000
#        minimumIdle: 5
#        maximumPoolSize: 20
#        idleTimeout: 30000
#        connectionTimeout: 30000
#        maxLifetime: 2000000
#        poolName: HikariPool
  mvc:
    view:             # JSP views
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: 'true'

  jpa:
  show-sql: true
  properties:
    hibernate:
      default_batch_fetch_size: 1000
  hibernate:
    ddl-auto: create

mybatis:
  type-aliases-package: com.example.moviezip.domain
  #  mapper-locations: com/example/jpetstore/dao/mybatis/mapper/**/*.xml

logging:
  level:
    com:
      example:
        moviezip:
          dao:
            mybatis:
              mapper: DEBUG

server:
  port: 8080